### ISSUE TITLE
Prefab list for npc

### ISSUE THREAD

**Issue by rafadsm** [NopeyBoi/ChatCommands#1]
Nice project bro, can u add Prefab list for NPC's?
Thanks!

**Comment by NopeyBoi** [comment]
Keep in mind that the spawn command has a few problems with spawning non VBlood NPCs. Here's a list tho:
https://github.com/NopeyBoi/ChatCommands/blob/main/Spawnable%20NPCs%20-%20June%2012th%202022.txt
