### ISSUE TITLE
Blood potions work fine, but blood command doesnt apply the blood buff only the ui look

### ISSUE THREAD

**Issue by tomyshoam** [NopeyBoi/ChatCommands#2]
Title pretty much says it all, tested it with the scholar buff, you dont get any resets.
also it seems like if you drink a blood potion and then change your blood using the blood command the ui changes to show the new blood ( from the blood command ) but the effects of the blood potions you had earlier remain

**Comment by NopeyBoi** [comment]
Yeah.. That is known. I already know what the problem should be but fixing that is another thing. Will see what I can do.

**Comment by NopeyBoi** [comment]
That command will be removed as bloodpotion does a better job.
