### ISSUE TITLE
Can you give %100 Blood Potions in Kits?

### ISSUE THREAD

**Issue by Aelfriclake** [NopeyBoi/ChatCommands#3]
Question in the title. Blood potion defaults to frailed if i'm correct.

**Comment by NopeyBoi** [comment]
Not with the current GUID system. I could make it work with a little bit tricksies tho. On my to-do list!

**Comment by Aelfriclake** [comment]
Yeah on Instant Duel servers that would be really useful.

**Comment by NopeyBoi** [comment]
Will be available with the newest release
