### ISSUE TITLE
How to install ??

### ISSUE THREAD

**Issue by oscarpedrero** [NopeyBoi/ChatCommands#5]
How to install, need compile first?

**Comment by NopeyBoi** [comment]
Download it here:
https://v-rising.thunderstore.io/package/Nopey/ChatCommands/

**Comment by oscarpedrero** [comment]
Install BepInExPack V Rising in folder VRisingServer_Data of server and dll in VRisingServer_Data/Plugin and dont work

**Comment by NopeyBoi** [comment]
You install BepInEx in the top level folder, aka the one with the VRisingServer.exe.
Then you start the server once to generate bepinex folders.
And then you can install the mod to "BepInEx/plugins" or "BepInEx/WetstonePlugins".
Keep in mind that you will have to install Wetstone as well.
