### ISSUE TITLE
Sunimmunity command issues

### ISSUE THREAD

**Issue by Valderg** [NopeyBoi/ChatCommands#6]
Sunimmunity command is permanent, when toggled off it stays off for a few minutes but seems like it updates a minute or two later and applys sunimmunity again. Tried disabling it then uninstalling and it still keeps sunimmunity.

**Comment by NopeyBoi** [comment]
That is a known issue. I am currently working on a reworked version of ChatCommands that will have that fixed. Until then you could look into RPGMods since that's a Mod that's based on ChatCommands command system.
https://v-rising.thunderstore.io/package/RPGMods/RPGMods/

**Comment by KatyMcBlagg** [comment]
Hi, I'm having this problem. Cannot get rid of the sunimmunity being permanent, even removing the mod itself. Is there a fix for this or a how to to get it deleted without affecting my game save?
